### ISSUE TITLE
Tree-of-Attack not included yet?

### ISSUE THREAD

**Issue by shizhouxing** [Sizhe-Chen/StruQ#2]
Hello authors! Is it right that the current code doesn't contain tree-of-attack?  I saw there is a comment saying that [test_tap should be used](https://github.com/Sizhe-Chen/StruQ/blob/main/run.py#L87) but this file has not been included? Since it seems to be the strongest attack in the paper, I was wondering if you could also release your modified tree-of-attack? Thanks a lot!

**Comment by Sizhe-Chen** [comment]
Thanks for your interest! Yes, TAP is not included in this repo. To test the strongest attacks, please use our latest test_gcg.py, which uses gradient-based optimization and is much stronger than TAP.
