### ISSUE TITLE
Request for the Aligned Model Weights

### ISSUE THREAD

**Issue by Raytsang123** [Sizhe-Chen/StruQ#3]
Hi, this work represents a significant advancement in the field of prompt injection defense. It seems that the aligned model weights were previously released in the earlier version of this repo. Could the authors release the weights again to facilitate further research? Thanks a lot!

**Comment by Sizhe-Chen** [comment]
Sure. They are still released in setup.py. Use python setup.py --model for automatic download.Best Regards,Sizhehttps://sizhe-chen.github.ioOn Dec 18, 2024, at 22:49, Rui Zeng ***@***.***> wrote:﻿
Hi, this work represents a significant advancement in the field of prompt injection defense. It seems that the aligned model weights were previously released in the earlier version of this repo. Could the authors release the weights again to facilitate further research? Thanks a lot!

**Comment by Raytsang123** [comment]
Oh, I'm sorry that I missed the file `setup.py`. Thank you for your patience and kindness! I will close this issue.
